version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sathi
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PGPASSWORD=postgres
      - API_PORT=8090
      - DB_ENABLE_SSL=false
    ports:
      - 8090:8090
    # command: npm run prod

  nginx:
    restart: always
    image: nginx:1.22.1-alpine
    depends_on:
      - db
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certificates:/usr/share/nginx/sathi-certificates
      - ./api/deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ui/build:/var/www/html
      - ./ui/build:/usr/share/nginx/html

volumes:
  postgres-data:
